apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  apiVersion: tekton.dev/v1beta1
  name: java
  namespace: demo-app

spec:
  params:
  - name: GITHUB_REPO_URL
    description: The application repository 
    default: 'https://github.com/mayurdeshmukh/quarkus-random-generator'

  - name: GITHUB_REPO_REVISION
    description: Git Repo Revision
    default: 'master'


  - name: IMAGE
    description: Name (reference) of the image to build.
    default: latest

  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile

  - name: CONTEXT
    description: The build context used by Kaniko.
    default: ./

  - name: EXTRA_ARGS
    default: ""

  - name: MAVEN_IMAGE
    default: gcr.io/cloud-builders/mvn



  tasks:
    - name: git-clone
      params:
        - name: url
          value:  $(params.GITHUB_REPO_URL)

        - name: revision
          value:  $(params.GITHUB_REPO_REVISION)
       

        - name: gitInitImage
          value: >-
            gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
        
        - name: deleteExisting
          value: 'true'

      workspaces:
      - name: output
        workspace: my-workspace

      taskRef:
        kind: Task
        name: git-clone
 
    - name: maven-build
      params:
        - name: GOAL
          value: 
            - clean
            - install

        - name: MAVEN_IMAGE
          value: $(params.MAVEN_IMAGE)

      taskRef:
        kind: ClusterTask
        name: maven
      
      runAfter:
      - git-clone

      workspaces:
      - name: source
        workspace: my-workspace

      - name: maven-settings
        workspace: maven-settings


    - name: docker-build
      params:
        - name: CONTEXT
          value:  $(params.CONTEXT)

        - name: DOCKERFILE
          value:  $(params.DOCKERFILE)
        
        - name: IMAGE
          value: $(params.IMAGE)

      taskRef:
        kind: ClusterTask
        name: buildah

      runAfter:
      - maven-build

      workspaces:
      - name: source
        workspace: my-workspace

  workspaces:
    - name: my-workspace
    - name: maven-settings
